#!/bin/bash

DOCKER_OPTS="-v `pwd`:/go/src/github.com/cstpdk/blueprint-parser \
		$EXTRA_DOCKER_OPTS"

TO_RUN="$@"

case "$1" in
	"--bash") DOCKER_OPTS="$DOCKER_OPTS --entrypoint bash" ; shift ;
		TO_RUN="-c \"$@\"";;
	"--build") DOCKER_OPTS="$DOCKER_OPTS --entrypoint bash" ; shift ;
		TO_RUN='-c "go install && blueprint-parser '"$@"'"' ;;
esac

eval docker run $DOCKER_OPTS blueprint-parser "$TO_RUN"
